name: Rails Docker CI Pipeline

on:
  workflow_dispatch:
  # For testing purposes, I am currently running the pipeline manually; however, to meet enterprise requirements, 
  # it should run automatically on push and pull request events for the relevant branches. 
  # At the moment, I have commented out the push and pull request triggers in the pipeline configuration.
  # push:
  #     branches: [ main ]
  # pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # -----------------------
    # 1. Checkout
    # -----------------------
      - name: Checkout repository
        uses: actions/checkout@v4

    # -----------------------
    # 2. Build Imand and Start Container
    # -----------------------

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Start application containers
        run: |
          docker-compose up -d 
                 
      - name: Wait for services to be ready
        run: |
          sleep 20

      - name: Build Tailwind CSS
        run: |
          docker exec ruby_appsec_web_1 rails tailwindcss:build

    # -----------------------
    # 3. Creating User
    # -----------------------

      - name: Seed Database (optional)
        run: |
          docker exec ruby_appsec_db_1 psql -U postgres -d sql_injection_dev -c "INSERT INTO users (email, encrypted_password, created_at, updated_at) VALUES ('${{ secrets.USER_NAME }}', '${{ secrets.PASSWORD }}', '2025-01-15 10:30:00'::timestamp, '2025-01-15 10:30:00'::timestamp);"
          docker exec ruby_appsec_db_1 psql -U postgres -d sql_injection_dev -c "SELECT * FROM users;"

    # I have not enforced any additional blocking conditions in the pipeline at this stage due to the issues identified. 
    # However, in an enterprise DevSecOps setup, security tollgates can be introduced based on organizational requirements. 
    # For example, thresholds can be defined for High or Medium severity findings, or an exception approval workflow can be 
    # added as a separate step in the job. Based on the organization’s risk appetite and emergency release policies, deployments 
    # can be conditionally approved by the CISO or designated security authority.
    
    # Example (conceptual DevSecOps gate step):
    
    # Fail the pipeline if High severity vulnerabilities are detected
    
    # Allow Medium severity findings with a documented exception
    
    # Add a manual approval step for emergency releases requiring CISO sign-off
  
    # -----------------------
    # 4. Initiating DAST Scan
    # -----------------------

      - name: DAST
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
           mkdir -p zap_reports
           chmod 777 zap_reports
           docker run --rm --network ruby_appsec_zapnet \
            -v $(pwd)/zap:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            env USER_NAME=$USER_NAME PASSWORD=$PASSWORD \
            zap-full-scan.py \
            -d \
            -n auth.context \
            -t http://ruby_appsec_web_1:8880 \
            -J zap_reports/zap_report.json

    # -----------------------
    # 5. Uploading Result
    # ----------------------- 

      # - name: Upload DAST Vul to DefectDojo
      #   run: |
      #     curl -X POST 'https://demo.defectdojo.org/api/v2/reimport-scan/' \
      #       -H 'accept: application/json' \
      #       -H 'Authorization: Token ${{ secrets.DEFECT_DOJO_TOKEN }}' \
      #       -F 'test=46' \
      #       -F 'active=true' \
      #       -F '[email protected];type=application/json' \
      #       -F file=@"zap_report.json" \
      #       -F 'scan_type=ZAP Scan' \
      #       -F 'tags=test'

    # -----------------------
    # 5. Stopping Containers
    # -----------------------

      - name: Stop containers
        if: always()
        run: |
          docker-compose down
