name: Rails Docker CI Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Start application containers
        run: |
          docker-compose up -d 
        #docker network create zapnet
          
      - name: Wait for services to be ready
        run: |
          sleep 20

      - name: Verify application is running
        run: |
          docker-compose ps
          docker exec ruby_appsec-zap-1 curl --fail http://localhost:8880 || exit 1

      - name: Seed Database (optional)
        run: |
          
          docker exec ruby_appsec_db_1 psql -U postgres -d sql_injection_dev -c "INSERT INTO users (email, encrypted_password, created_at, updated_at) VALUES ('${{ secrets.USER_NAME }}', '${{ secrets.PASSWORD }}', '2025-01-15 10:30:00'::timestamp, '2025-01-15 10:30:00'::timestamp);"
          docker exec ruby_appsec_db_1 psql -U postgres -d sql_injection_dev -c "SELECT * FROM users;"
        #  docker exec ruby_appsec_web_1 bash -c "rake db:seed"

      
      # - name: Run ZAP Docker
      #   run: |
      #     mkdir -p zap_reports
      #     chmod 777 zap_reports
      #     docker run --rm \
      #     --name ruby_appsec_zap_1 \
      #     zap-baseline.py -t http://ruby_appsec_web_1:8880 -J zap_report.json -d || true

      - name: Run ZAP Baseline Scan (via Docker)
        run: |
          docker exec ruby_appsec-zap-1 zap-baseline.py -t http://ruby_appsec_web_1:8880 -J zap_report.json -d || true
        
          
    #      docker run --rm --network ruby_appsec_default \
     #       -v $(pwd)/zap_reports:/zap/wrk \
      #      ghcr.io/zaproxy/zaproxy:stable \
       #     zap-baseline.py -t http://ruby_appsec_web_1:8880 -J zap_report.json -d || true   

      

      - name: Stop containers
        if: always()
        run: |
          docker-compose down
