name: Rails Docker CI Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Start application containers
        run: |
          docker-compose up -d

      - name: Wait for services to be ready
        run: |
          sleep 20

      - name: Seed Database (optional)
        run: |
          docker exec ruby_appsec_web_1 bash -c "rake db:seed"
          docker exec ruby_appsec_db_1 psql -U postgres -d sql_injection_dev -c "INSERT INTO users (email, encrypted_password) VALUES ('${{ secrets.USER_NAME }}', '${{ secrets.PASSWORD }}');"
          docker exec ruby_appsec_db_1 psql -U postgres -d sql_injection_dev -c "SELECT * FROM users;"

      - name: Verify application is running
        run: |
          docker-compose ps
          curl --fail http://localhost:8880 || exit 1

      - name: Stop containers
        if: always()
        run: |
          docker-compose down
