name: Ruby DevSecOps Pipeline

on:
  workflow_dispatch:
  # For testing purposes, I am currently running the pipeline manually; however, to meet enterprise requirements, 
  # it should run automatically on push and pull request events for the relevant branches. 
  # At the moment, I have commented out the push and pull request triggers in the pipeline configuration.
  # push:
  #     branches: [ main ]
  # pull_request:

permissions:
  contents: read

jobs:
  Security:
    runs-on: ubuntu-latest

    steps:
    # -----------------------
    # 1. Checkout
    # -----------------------
      - name: Checkout code
        uses: actions/checkout@v4
        
    # -----------------------
    # 2. Setup Ruby
    # -----------------------
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
                    
    # I have not enforced any additional blocking conditions in the pipeline at this stage due to the issues identified. 
    # However, in an enterprise DevSecOps setup, security tollgates can be introduced based on organizational requirements. 
    # For example, thresholds can be defined for High or Medium severity findings, or an exception approval workflow can be 
    # added as a separate step in the job. Based on the organization’s risk appetite and emergency release policies, deployments 
    # can be conditionally approved by the CISO or designated security authority.
    
    # Example (conceptual DevSecOps gate step):
    
    # Fail the pipeline if High severity vulnerabilities are detected
    
    # Allow Medium severity findings with a documented exception
    
    # Add a manual approval step for emergency releases requiring CISO sign-off

    # -----------------------
    # 3. SBOM 
    # -----------------------
      - name: Generate SBOM
        run: |
          gem install cyclonedx-ruby
          cyclonedx-ruby -p . -o sbom.json
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

    # -----------------------
    # 4. Secrets Scan - Gitleaks
    # -----------------------
      - name: Secret Scanning 
        continue-on-error: true
        run: |
          sudo apt install gitleaks
          gitleaks detect -v --report-format=json --report-path=gitleaks.json --log-level=debug
      - name: Upload secrets Vul to DefectDojo
        run: |
          curl -X POST 'https://demo.defectdojo.org/api/v2/reimport-scan/' \
            -H 'accept: application/json' \
            -H 'Authorization: Token ${{ secrets.DEFECT_DOJO_TOKEN }}' \
            -F 'test=45' \
            -F 'active=true' \
            -F '[email protected];type=application/json' \
            -F file=@"gitleaks.json" \
            -F 'scan_type=Gitleaks Scan' \
            -F 'tags=test'

  # -----------------------
  # 5. SCA - Bundler Audit
  # -----------------------          
      - name: Dependency Scan - Bundler Audit
        continue-on-error: true
        run: |
          gem install bundler-audit
          bundle-audit update
          bundle-audit check --format json --output bundle-audit.json
      - name: Upload bundleAudit to DefectDojo
        run: |
          cat bundle-audit.json
          curl -X POST 'https://demo.defectdojo.org/api/v2/reimport-scan/' \
            -H 'accept: application/json' \
            -H 'Authorization: Token ${{ secrets.DEFECT_DOJO_TOKEN }}' \
            -F 'test=44' \
            -F 'active=true' \
            -F '[email protected];type=application/json' \
            -F file=@"bundle-audit.json" \
            -F 'scan_type=Bundler-Audit Scan' \
            -F 'tags=test'
          
  # -----------------------
  # 6. SAST - Brakeman
  # -----------------------         
      - name: SAST testing
        run: |
            gem install brakeman
            brakeman --no-exit-on-warn --no-exit-on-error -f json -o brakeman.json    
      - name: Upload SAST Vul to DefectDojo
        run: |
          curl -X POST 'https://demo.defectdojo.org/api/v2/reimport-scan/' \
            -H 'accept: application/json' \
            -H 'Authorization: Token ${{ secrets.DEFECT_DOJO_TOKEN }}' \
            -F 'test=43' \
            -F 'active=true' \
            -F '[email protected];type=application/json' \
            -F file=@"brakeman.json" \
            -F 'scan_type=Brakeman Scan' \
            -F 'tags=test'
          
  # -----------------------
  # 7. Upload Artifacts
  # -----------------------
      - name: Upload Security Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            gitleaks.json
            brakeman.json
            bundle-audit.json
            sbom.json
