name: Ruby DevSecOps Pipeline

on:
  workflow_dispatch:
  # For testing purposes, I am currently running the pipeline manually; however, to meet enterprise requirements, 
  # it should run automatically on push and pull request events for the relevant branches. 
  # At the moment, I have commented out the push and pull request triggers in the pipeline configuration.
  # push:
  #     branches: [ main ]
  # pull_request:

permissions:
  contents: read

jobs:
  Security:
    runs-on: ubuntu-latest

    steps:
    # -----------------------
    # 1. Checkout
    # -----------------------
      - name: Checkout code
        uses: actions/checkout@v4
        
    # -----------------------
    # 2. Setup Ruby
    # -----------------------
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
                    
      # - name: Setup Dependencies
      #   run: |
      #     gem install bundler
      #     bundle install

      - name: Generate SBOM
        run: |
          gem install cyclonedx-ruby
          cyclonedx-ruby -p . -o sbom.json
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

    # -----------------------
    # 3. Secrets Scan - Gitleaks
    # -----------------------
      - name: Secret Scanning 
        continue-on-error: true
        run: |
          sudo apt install gitleaks
          gitleaks detect -v --report-format=json --report-path=gitleaks.json --log-level=debug
      - name: Upload bundleAudit to DefectDojo
        run: |
          curl -X POST 'https://demo.defectdojo.org/api/v2/reimport-scan/' \
            -H 'accept: application/json' \
            -H 'Authorization: Token ${{ secrets.DEFECT_DOJO_TOKEN }}' \
            -F 'test=37' \
            -F 'active=true' \
            -F '[email protected];type=application/json' \
            -F file=@"gitleaks.json" \
            -F 'scan_type=Gitleaks Scan' \
            -F 'tags=test'
      # - name: Upload Gitleaks Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: gitleak-report
      #     path: gitleaks.json

  # -----------------------
  # 4. SCA - Bundler Audit
  # -----------------------          
      - name: Dependency Scan - Bundler Audit
        continue-on-error: true
        run: |
          gem install bundler-audit
          bundle-audit update
          bundle-audit check --format json --output bundle-audit.json
      - name: Upload bundleAudit to DefectDojo
        run: |
          cat bundle-audit.json
          curl -X POST 'https://demo.defectdojo.org/api/v2/reimport-scan/' \
            -H 'accept: application/json' \
            -H 'Authorization: Token ${{ secrets.DEFECT_DOJO_TOKEN }}' \
            -F 'test=35' \
            -F 'active=true' \
            -F '[email protected];type=application/json' \
            -F file=@"bundle-audit.json" \
            -F 'scan_type=Bundler-Audit Scan' \
            -F 'tags=test'
          
      # - name: Upload bundleAudit Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: bundle-audit-report
      #     path: bundle-audit.json

  # -----------------------
  # 5. SAST - Brakeman
  # -----------------------         
      - name: SAST testing
        run: |
            gem install brakeman
            brakeman --no-exit-on-warn --no-exit-on-error -f json -o brakeman.json    
      - name: Upload bundleAudit to DefectDojo
        run: |
          curl -X POST 'https://demo.defectdojo.org/api/v2/reimport-scan/' \
            -H 'accept: application/json' \
            -H 'Authorization: Token ${{ secrets.DEFECT_DOJO_TOKEN }}' \
            -F 'test=36' \
            -F 'active=true' \
            -F '[email protected];type=application/json' \
            -F file=@"sast_fin.json" \
            -F 'scan_type=Brakeman Scan' \
            -F 'tags=test'
          
      # - name: Upload SAST-Finding Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: SAST-Finding-Report
      #     path: sast_fin.json

  # -----------------------
  # 9. Upload Artifacts
  # -----------------------
      - name: Upload Security Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            gitleaks.json
            brakeman.json
            bundle-audit.json
            sbom.json

      - name: Secret Scanning
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
          trufflehog --version
          trufflehog git https://github.com/${{ github.repository }} --json > trufflehog_results.json
      - name: Upload TruffleHog Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog_results.json

      #  - name: Secrets Scan - Gitleaks
     #   run: |
      #    docker pull ghcr.io/gitleaks/gitleaks:latest
       #   docker run -v https://github.com/${{ github.repository }}:/path ghcr.io/gitleaks/gitleaks:latest git -v --source=/path --report-format json --report-path /path/gitleaks.json
            
      # - name: Debug - List files
      #   run: ls -la
       
#      - name: Linting and Styling
#        run: |
#          gem install rubocop
#          rubocop -a

      #bundle-audit
  #Dependency-Scan:
   # runs-on: ubuntu-latest
    #needs: build
    #permissions:
    #  security-events: write
    #steps:

      # - name: Run Unit Tests
      #   run: |
      #     gem install rspec
      #     rspec
