name: DAST SCAN

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: zaproxy/action-af@main
        with: 
        plan: 'zap/plan.yml'

      - name: Upload Security Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: security-reports
            path: |
              report.pdf
