name: Rails Docker CI Pipeline Zap

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create reports folder
        run: mkdir -p reports

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: |
          docker-compose build
          

      - name: Start application containers
        run: |
          docker compose up -d || echo "ZAP scan completed with findings"
        #docker network create zapnet
          
      - name: Wait for services to be ready
        run: |
          sleep 20

      - name: Verify application is running
        run: |
          docker-compose ps
          curl --fail http://localhost:8880 || exit 1

     # - name: Seed Database (optional)
     #   run: |
     #     
     #     docker exec ruby_appsec_db_1 psql -U postgres -d sql_injection_dev -c "INSERT INTO users (email, encrypted_password, created_at, updated_at) VALUES ('${{ secrets.USER_NAME }}', '${{ secrets.PASSWORD }}', '2025-01-15 10:30:00'::timestamp, '2025-01-15 10:30:00'::timestamp);"
     #     docker exec ruby_appsec_db_1 psql -U postgres -d sql_injection_dev -c "SELECT * FROM users;"
        #  docker exec ruby_appsec_web_1 bash -c "rake db:seed"

      
      - name: Copy ZAP reports from container
        run: |
          ZAP_CONTAINER=$(docker ps -aqf "name=ruby_appsec-zap-1")
          docker cp "$ZAP_CONTAINER":/tmp/zap-report.html reports/zap-report.html || echo "No HTML report found"
          docker cp "$ZAP_CONTAINER":/tmp/zap-report.json reports/zap-report.json || echo "No JSON report found"

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: reports/zap-report.html

      - name: Verify application is running
        run: |
          docker-compose ps
          curl --fail http://localhost:8880 || exit 1

      - name: Stop containers
        if: always()
        run: |
          docker-compose down
